version: '3.7'
services:
  zookeeper:
    image: strimzi/kafka:latest-kafka-2.6.0
    hostname: zookeeper
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
        - "2181:2181"
    environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
        - LOG_DIR=/tmp/logs
    volumes:
        - ./data/zookeeper/data:/data
        - ./data/zookeeper/datalog:/datalog
  kafka:
      image: strimzi/kafka:latest-kafka-2.6.0
      hostname: kafka
      command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
      ]
      ports:
          - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        LOG_DIR: /tmp/logs
      volumes:
        - ./data/kafka/data:/var/lib/kafka/data
        - /var/run/docker.sock:/var/run/docker.sock
        - .:/home          
      depends_on:
      - zookeeper
  simulator:
    image: ibmcase/eda-store-simulator
    depends_on:
      - kafka
    hostname: storeapp
    ports:
      - "8080:8080"
      